### ISSUE TITLE
Understanding Burrito output

### ISSUE THREAD

**Issue by amoltej** [borenstein-lab/burrito#20]
Hi, 
I performed burrito analysis but due to no replicates, I did not get all the output files.
Currently I have only `burrito_function_abundance.tab` and `burrito_ocntribution.tab` files
I am trying to understand and replicate burrito analysis because the functions (subpathway level) that I am focusing on are extremely difficult to visualize with the burrito's current interface due to small numbers and visual limitations.
When I tried to match the % contribution showed on burrito analysis by the server and calculating the same contribution from the `burrito_contribution.tab` file, it did not match.
can you please help me understand how can I use these files to compare functions and OTU abundance manually? and replicate these results for specific function only?
What does the contribution number represent in the table?
`burrito_function_abundance.tab` just shows the universal function and not OTU based and hence it may not be useful in my case. 
But what do these numbers represent?
which number represent OTU abundance? 
I am uploading 1) Taxonomic abundance, 2) taxonomy 3) metagenome abundance 4) metagenome attribution and 5) metadata files for burrito analysis

Thank you

**Comment by engal** [comment]
Hi,

Unfortunately, it looks like there might have been an issue in uploading your data, so I cannot answer any data-specific issues you are experiencing. However, I might be able to offer some help.

First, when you are comparing your downloaded contribution file to the visualization, which numbers are you comparing? The "Contribution" column should match the "Attribution of Total" number in the tooltip, but divided by 100 (e.g. 0.013 in the downloaded contribution table would appear as 1.3% in the visualization).

I should also mention, the contribution table that you can download from BURRITO is made available for users using the automatic or genomic content taxonomy-function linking methods. If you are uploading your own contribution table (e.g. PICRUSt2 stratified output), then you will already have any data presented in the BURRITO visualization.

Our output files do not include OTU abundances since that is part of the required input. Thus, you should already have access to that data.

This is the best I can do without your data files, or any specific examples of inconsistencies you find between your data and the BURRITO visualization that I can look into.

Hope that helps!

**Comment by amoltej** [comment]
Hi Alex,

Thanks for the explanation. 
[https://1drv.ms/u/s!AnutfSj9fsoTqStBy-ZkDKwpEQhl?e=QJngGX](url)

It clarifies the output question.
I have uploaded files just because you feel there might be an issue with data. Could you please have a look at it?
Thanks for your time.
Amol

**Comment by engal** [comment]
Hi Amol,

I just tried it out and your data looks fine.

Please let me know if you have any other questions.

Best,
Alex
