### ISSUE TITLE
Burrito input from Picrust2

### ISSUE THREAD

**Issue by PauObregon** [borenstein-lab/burrito#21]
Dear all,
I used picrust2 to make functional predictions on my 16S rRNA data. I am a little confused, as I have many outputs from the whole pipeline and don't know which ones are required for BURRITO to assemble the functional profiles. I am using these ones, but having errors in the BURRITO assembly (The following OTU_IDs are in the OTU table but are not present in the PICRUSt 16S normalization table):
- Feature table of the ASVs (in tsv), with the frequences in each sample
- KO_predicted count for each ASV (tsv)
- Metadata file (tsv)
I've read in other post that the flag --stratified in picrust2 could be of help, but I didn't manage to assemble the BURRITO.
Any help will be much appreciated!!

**Comment by PauObregon** [comment]
Dear engal,
I mannaged to correctly assemble the burrito,
Thanks a lot for your help!

**Comment by Theda-sys** [comment]
Hello,

So here is my problem: 
I am using the LotuS_SLV138 to process the data. Running PiCrust with this is no problem, and i am using the following commands to get the output: 
picrust2_pipeline.py -s clean-seqs.fa \
-i clean-rarefied-abun.tsv \
-o output \
-p 8 \
--stratified \
--per_sequence_contrib \
--verbose

Now I am very excited to use the BURRITO thingy, however I have no Idea what to use for the upload? And than which of the options to select:
Is it possible to use KO_predicted.tsv for "Custom genomic content table" option for the taxonomy-function linking method?
What do I have to use as Taxonomic Data, and is it even possible when the data was processed with LotuS?? 

I am really appricate help!!
Thanks,
me

**Comment by engal** [comment]
Hi,

You are correct, you can use the KO_predicted.tsv for the "Custom genomic content table" option, and you should be able to use the associated abundance table for taxonomy (i.e. the "clean-rarefied-abun.tsv" file you used for PiCRUSt input).

The primary component you may be missing is a taxonomy file which specifies the hierarchical taxonomic relationships between taxa (see example on upload page for formatting). Since you are not using Greengenes OTUs, you will need to supply such a taxonomy file with the "Custom taxonomy" option. If you have a very small number of taxa in your dataset, you could potentially use the "Custom taxon IDs with no hierarchy" option, but if you have more than ~20-50 taxa, this option is probably not ideal.

Best,
engal
