### ISSUE TITLE
The following OTUs are in the contribution table but are not present in the OTU table

### ISSUE THREAD

**Issue by elayton13** [borenstein-lab/burrito#29]
Hello

I have been trying for a while now to figure out what I need to input into burrito but just can't get it working. I have been trying with 3 input files: taxonomic abundances (run1_otu.tsv), a custom taxonomy file generated in Qiime2 (run1_taxtable.tsv) and a function attribution table from picrust2, converted to legacy format (pred_metagenome_contrib.legacy.tsv). I am getting the following error:

The following OTUs are in the contribution table but are not present in the OTU table: 1ce9ca503371cf3bbb4840adf2156d10 5bcee2d3ac9b08fc21ab3046a8587aa4 736cb3faf54c849d63102f34f320fc86 73a5f1b59a1fcb80365c898bdc55091a a680f264a2de7c45d7ab5907464dcc14 e0818b0e6493ef5ca9f447479e894888 694c36d13e5eb396f4d549a1af9ad696 45f77a09a3b22f2553c4f30960da884e 69fa289665344dd550f6b7c5cba3742e 4c2769b349dbba1580d7f2ad0e5c5a1d 32b13baed6bd21e159d8fc7b36192a6b 34ba620a2a73a73fd64f27d6e6877b71 96cdd332d0b871def37303e76ba848f7 76915dfa0fb84d53e213bf4631abb6b2 1235a1b3e67af34a123d79aad2e82a6c 46014047d4934348dd524617e154be0c 575e9ac2104fc2bd50b4b439ae003efc 6146e12059e929948365636a97998223 f1f50b28babfa2d92e250f493d0e04bc f6bab11e87da5a6dcd99ad55278f567e 448d1e5975e07ec6c0604b22a35948d3 2675ec31b837dee45d48849053ca3d5c

I have attached my input files (for running burrito I am using the unzipped versions)

[run1_otu.tsv.gz](https://github.com/borenstein-lab/burrito/files/8320269/run1_otu.tsv.gz)
[run1_taxtable.tsv.gz](https://github.com/borenstein-lab/burrito/files/8320272/run1_taxtable.tsv.gz)
[pred_metagenome_contrib.legacy.tsv.gz](https://github.com/borenstein-lab/burrito/files/8320273/pred_metagenome_contrib.legacy.tsv.gz)

I have checked the first few and they seem to be present in all 3 files. Your advice would be appreciated!

**Comment by engal** [comment]
Hi,

Quick note, you can use the zipped versions of the files for burrito, that should speed up the upload process.

I think the confusing error message is due to an incorrect ordering in burrito's data validation. The more helpful error message would indicate that there are samples in your function attribution table that are not present in your taxonomic abundance table. I looked through a few of the taxa reported as missing from the OTU table, and it looks like they have zero abundance across all samples (which burrito filters out automatically), but still appear in the function attribution table with non-zero abundance due to the presence of extra samples. If you remove the additional samples from the function attribution table, I think this will fix the issue.

I'm going to update the data validation process so that the more helpful error message will appear in the future.

**Comment by elayton13** [comment]
Yes that fixed it thank you!
